### PR TITLE
Adding proof using annotation.

### PR DESCRIPTION
**Pull request by ahmet-celik**

### CODE REVIEW

**Comment by wilcoxjay** [comment]
Hello @ahmet-celik,

Thank you very much for the PR! We had been talking about adding these annotations just this week, so you have great timing!

Before I merge this, would you mind undoing the changes that remove the last newline of each file? If this is too much trouble, just let me know, and I can do it when I merge.

Thanks again!

James

**Comment by palmskog** [comment]
Unless Ahmet can do it really quickly, I can take care of the newline thing in a separate branch, along with some small manual adjustments. (Yes, I asked Ahmet to do these changes, but wasn't prepared for full-blown PR this quickly.)

**Comment by wilcoxjay** [comment]
That makes sense. 

Since there is no way to change the branch on a Github PR, either Ahmet will need to push these changes, or we will need to close this PR and open a separate one for Karl's branch.

**Comment by ahmet-celik** [comment]
Your welcome.
I added the last newline of each file.
Thanks,
Ahmet

**Comment by palmskog** [comment]
I think this looks good enough to be merged on its own now, so @wilcoxjay feel free to do that if you agree. 

However, to get the full benefit of the quick compilation toolchain, there are still some changes that need to be made in makefiles and in other places, but I think that should go in separate PRs.

Thanks again Ahmet!

**Comment by wilcoxjay** [comment]
Sounds good, merging!

**Pull request merged**
